"""empty message

Revision ID: 61795e418e38
Revises: e76c33d3c2ee
Create Date: 2020-05-30 19:00:14.776285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61795e418e38'
down_revision = 'e76c33d3c2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
